stages:
- name: Build
  steps:
  - runScriptConfig:
      shellScript: |-
        mkdir -p /java/src/github.com/rancher
        ln -s `pwd` /java/src/github.com/rancher/docker-demo
        cd /java/src/github.com/rancher/docker-demo
        mvn clean install
        mvn package
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: docker-demo:${CICD_EXECUTION_SEQUENCE}
      registry: index.docker.io
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
notification:
  recipients:
  - recipient: ch.xi@onedayapp.cn
    notifier: local:n-kslqj
  condition:
  - Success
  - Failed
